from __future__ import annotations

COL_USERS = "users"
COL_VERIFICATION = "verification_codes"
COL_MESSAGES = "messages"
COL_MESSAGE_RECEIPTS = "message_receipts"
COL_REFRESH_TOKENS = "refresh_tokens"
COL_PASSKEYS = "passkeys"
COL_PASSKEY_CHALLENGES = "passkey_challenges"
COL_PINGS = "pings"
COL_DISCOVERY_TOKENS = "discovery_tokens"
COL_CALLS = "calls"
COL_CONVERSATIONS = "conversations"
COL_CONVERSATION_PARTICIPANTS = "conversation_participants"
COL_DEVICES = "devices"
COL_DEVICE_PREKEYS = "device_prekeys"
