from __future__ import annotations

COL_USERS = "users"
COL_VERIFICATION = "verification_codes"
COL_MESSAGES = "messages"
COL_MESSAGE_RECEIPTS = "message_receipts"
COL_REFRESH_TOKENS = "refresh_tokens"
COL_PASSKEYS = "passkeys"
COL_PASSKEY_CHALLENGES = "passkey_challenges"
COL_PINGS = "pings"
COL_DISCOVERY_TOKENS = "discovery_tokens"
COL_CALLS = "calls"
COL_CONVERSATIONS = "conversations"
COL_CONVERSATION_PARTICIPANTS = "conversation_participants"
COL_DEVICES = "devices"
COL_DEVICE_PREKEYS = "device_prekeys"
# finalize-messenger-conversation-model
COL_SPACES = "spaces"
COL_SPACE_MEMBERS = "space_members"
COL_INVITE_LINKS = "invite_links"
COL_JOIN_REQUESTS = "join_requests"
COL_BLOCKS = "blocks"
COL_PUSH_TOKENS = "push_tokens"
COL_SAVED_MESSAGES = "saved_messages"
COL_NOTIFICATIONS = "notifications"
COL_BOTS = "bots"
COL_WEBHOOKS = "webhooks"
COL_REPORTS = "reports"
COL_AUDIT_LOGS = "audit_logs"
