[mypy]
python_version = 3.12


ignore_missing_imports = True
disable_error_code = misc,arg-type,attr-defined,assignment,union-attr,var-annotated,import-untyped,annotation-unchecked

allow_untyped_defs = True
allow_untyped_globals = True

check_untyped_defs = False